# Generated by Django 4.1.7 on 2023-03-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=150)),
                ('Subject', models.CharField(max_length=250)),
                ('Mobile', models.IntegerField()),
                ('Email', models.EmailField(max_length=250)),
                ('Message', models.CharField(max_length=250)),
            ],
        ),
    ]
